# Generated by Django 4.2.3 on 2023-07-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dolist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do_object', models.TextField(max_length=100, verbose_name='할 일')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='작성일자')),
                ('finish_time', models.DateTimeField(null=True, verbose_name='완료일자')),
            ],
            options={
                'verbose_name_plural': '할 일 목록',
            },
        ),
    ]
